    include "m3dk_types.inc"

; Public API surface:
;   m3dk_init
;   m3dk_frame_begin
;   m3dk_frame_end
;   m3dk_present_frame
;   m3dk_clear_frame
;   m3dk_transform_scene
;   m3dk_render_scene
;   m3dk_draw_wireframe
;   m3dk_draw_visible_wireframe
;   m3dk_draw_solid
;   m3dk_set_active_mesh
;   m3dk_get_active_mesh
;   m3dk_set_scene_rotation
;   m3dk_set_camera
;   m3dk_get_pad_cur
;   m3dk_get_pad_press
;   m3dk_get_pad_ext_cur
;   m3dk_get_pad_ext_press
