    ifnd MEGA3DK_TYPES_INC
MEGA3DK_TYPES_INC   equ 1

VERT3_X      equ 0
VERT3_Y      equ 4
VERT3_Z      equ 8
VERT3_SIZE   equ 12
VERT2_X      equ 0
VERT2_Y      equ 2
VERT2_Z      equ 4
VERT2_SIZE   equ 8
FACE_I0      equ 0
FACE_I1      equ 2
FACE_I2      equ 4
FACE_COLOR   equ 6
FACE_SIZE    equ 8
EDGE_I0      equ 0
EDGE_I1      equ 2
EDGE_SIZE    equ 4
VFACE_I0     equ 0
VFACE_I1     equ 2
VFACE_I2     equ 4
VFACE_DEPTH  equ 6
VFACE_COLOR  equ 10
VFACE_SIZE   equ 12
    endif
